import { Team } from './team';

const TEAMS: Array<Team> = [
    {
        "isNBAFranchise": true,
        "city": "Atlanta",
        "altCityName": "Atlanta",
        "fullName": "Atlanta Hawks",
        "triCode": "ATL",
        "teamId": "1610612737",
        "nickname": "Hawks",
        "urlName": "hawks",
        "confName": "East",
        "divName": "Southeast"
    },
    {
        "isNBAFranchise": false,
        "city": "Barcelona",
        "altCityName": "Barcelona",
        "fullName": "Barcelona FC Barcelona",
        "triCode": "FCB",
        "teamId": "12304",
        "nickname": "FC Barcelona",
        "urlName": "fcbarcelona",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Boston",
        "altCityName": "Boston",
        "fullName": "Boston Celtics",
        "triCode": "BOS",
        "teamId": "1610612738",
        "nickname": "Celtics",
        "urlName": "celtics",
        "confName": "East",
        "divName": "Atlantic"
    },
    {
        "isNBAFranchise": true,
        "city": "Brooklyn",
        "altCityName": "Brooklyn",
        "fullName": "Brooklyn Nets",
        "triCode": "BKN",
        "teamId": "1610612751",
        "nickname": "Nets",
        "urlName": "nets",
        "confName": "East",
        "divName": "Atlantic"
    },
    {
        "isNBAFranchise": false,
        "city": "Buenos Aires",
        "altCityName": "Buenos Aires",
        "fullName": "Buenos Aires San Lorenzo",
        "triCode": "SLA",
        "teamId": "12330",
        "nickname": "San Lorenzo",
        "urlName": "san_lorenzo",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "city": "Canada Celebrities",
        "altCityName": "Canada Celebrities",
        "fullName": "Canada Celebrities Canada Celebrities",
        "triCode": "CAN",
        "teamId": "1610616839",
        "nickname": "Canada Celebrities",
        "urlName": "canada_celebrities",
        "confName": "East",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Charlotte",
        "altCityName": "Charlotte",
        "fullName": "Charlotte Hornets",
        "triCode": "CHA",
        "teamId": "1610612766",
        "nickname": "Hornets",
        "urlName": "hornets",
        "confName": "East",
        "divName": "Southeast"
    },
    {
        "isNBAFranchise": true,
        "city": "Chicago",
        "altCityName": "Chicago",
        "fullName": "Chicago Bulls",
        "triCode": "CHI",
        "teamId": "1610612741",
        "nickname": "Bulls",
        "urlName": "bulls",
        "confName": "East",
        "divName": "Central"
    },
    {
        "isNBAFranchise": true,
        "city": "Cleveland",
        "altCityName": "Cleveland",
        "fullName": "Cleveland Cavaliers",
        "triCode": "CLE",
        "teamId": "1610612739",
        "nickname": "Cavaliers",
        "urlName": "cavaliers",
        "confName": "East",
        "divName": "Central"
    },
    {
        "isNBAFranchise": true,
        "city": "Dallas",
        "altCityName": "Dallas",
        "fullName": "Dallas Mavericks",
        "triCode": "DAL",
        "teamId": "1610612742",
        "nickname": "Mavericks",
        "urlName": "mavericks",
        "confName": "West",
        "divName": "Southwest"
    },
    {
        "isNBAFranchise": true,
        "city": "Denver",
        "altCityName": "Denver",
        "fullName": "Denver Nuggets",
        "triCode": "DEN",
        "teamId": "1610612743",
        "nickname": "Nuggets",
        "urlName": "nuggets",
        "confName": "West",
        "divName": "Northwest"
    },
    {
        "isNBAFranchise": true,
        "city": "Detroit",
        "altCityName": "Detroit",
        "fullName": "Detroit Pistons",
        "triCode": "DET",
        "teamId": "1610612765",
        "nickname": "Pistons",
        "urlName": "pistons",
        "confName": "East",
        "divName": "Central"
    },
    {
        "isNBAFranchise": false,
        "city": "East",
        "altCityName": "East",
        "fullName": "East East",
        "triCode": "EST",
        "teamId": "1610616833",
        "nickname": "East",
        "urlName": "east",
        "confName": "East",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Golden State",
        "altCityName": "Golden State",
        "fullName": "Golden State Warriors",
        "triCode": "GSW",
        "teamId": "1610612744",
        "nickname": "Warriors",
        "urlName": "warriors",
        "confName": "West",
        "divName": "Pacific"
    },
    {
        "isNBAFranchise": false,
        "city": "Haifa",
        "altCityName": "Haifa",
        "fullName": "Haifa Maccabi Haifa",
        "triCode": "MAC",
        "teamId": "93",
        "nickname": "Maccabi Haifa",
        "urlName": "maccabi_haifa",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Houston",
        "altCityName": "Houston",
        "fullName": "Houston Rockets",
        "triCode": "HOU",
        "teamId": "1610612745",
        "nickname": "Rockets",
        "urlName": "rockets",
        "confName": "West",
        "divName": "Southwest"
    },
    {
        "isNBAFranchise": true,
        "city": "Indiana",
        "altCityName": "Indiana",
        "fullName": "Indiana Pacers",
        "triCode": "IND",
        "teamId": "1610612754",
        "nickname": "Pacers",
        "urlName": "pacers",
        "confName": "East",
        "divName": "Central"
    },
    {
        "isNBAFranchise": true,
        "city": "LA",
        "altCityName": "LA Clippers",
        "fullName": "LA Clippers",
        "triCode": "LAC",
        "teamId": "1610612746",
        "nickname": "Clippers",
        "urlName": "clippers",
        "confName": "West",
        "divName": "Pacific"
    },
    {
        "isNBAFranchise": true,
        "city": "Los Angeles",
        "altCityName": "L.A. Lakers",
        "fullName": "L.A. Lakers",
        "triCode": "LAL",
        "teamId": "1610612747",
        "nickname": "Lakers",
        "urlName": "lakers",
        "confName": "West",
        "divName": "Pacific"
    },
    {
        "isNBAFranchise": true,
        "city": "Memphis",
        "altCityName": "Memphis",
        "fullName": "Memphis Grizzlies",
        "triCode": "MEM",
        "teamId": "1610612763",
        "nickname": "Grizzlies",
        "urlName": "grizzlies",
        "confName": "West",
        "divName": "Southwest"
    },
    {
        "isNBAFranchise": true,
        "city": "Miami",
        "altCityName": "Miami",
        "fullName": "Miami Heat",
        "triCode": "MIA",
        "teamId": "1610612748",
        "nickname": "Heat",
        "urlName": "heat",
        "confName": "East",
        "divName": "Southeast"
    },
    {
        "isNBAFranchise": true,
        "city": "Milwaukee",
        "altCityName": "Milwaukee",
        "fullName": "Milwaukee Bucks",
        "triCode": "MIL",
        "teamId": "1610612749",
        "nickname": "Bucks",
        "urlName": "bucks",
        "confName": "East",
        "divName": "Central"
    },
    {
        "isNBAFranchise": true,
        "city": "Minnesota",
        "altCityName": "Minnesota",
        "fullName": "Minnesota Timberwolves",
        "triCode": "MIN",
        "teamId": "1610612750",
        "nickname": "Timberwolves",
        "urlName": "timberwolves",
        "confName": "West",
        "divName": "Northwest"
    },
    {
        "isNBAFranchise": true,
        "city": "New Orleans",
        "altCityName": "New Orleans",
        "fullName": "New Orleans Pelicans",
        "triCode": "NOP",
        "teamId": "1610612740",
        "nickname": "Pelicans",
        "urlName": "pelicans",
        "confName": "West",
        "divName": "Southwest"
    },
    {
        "isNBAFranchise": true,
        "city": "New York",
        "altCityName": "New York",
        "fullName": "New York Knicks",
        "triCode": "NYK",
        "teamId": "1610612752",
        "nickname": "Knicks",
        "urlName": "knicks",
        "confName": "East",
        "divName": "Atlantic"
    },
    {
        "isNBAFranchise": true,
        "city": "Oklahoma City",
        "altCityName": "Oklahoma City",
        "fullName": "Oklahoma City Thunder",
        "triCode": "OKC",
        "teamId": "1610612760",
        "nickname": "Thunder",
        "urlName": "thunder",
        "confName": "West",
        "divName": "Northwest"
    },
    {
        "isNBAFranchise": true,
        "city": "Orlando",
        "altCityName": "Orlando",
        "fullName": "Orlando Magic",
        "triCode": "ORL",
        "teamId": "1610612753",
        "nickname": "Magic",
        "urlName": "magic",
        "confName": "East",
        "divName": "Southeast"
    },
    {
        "isNBAFranchise": true,
        "city": "Philadelphia",
        "altCityName": "Philadelphia",
        "fullName": "Philadelphia 76ers",
        "triCode": "PHI",
        "teamId": "1610612755",
        "nickname": "76ers",
        "urlName": "sixers",
        "confName": "East",
        "divName": "Atlantic"
    },
    {
        "isNBAFranchise": true,
        "city": "Phoenix",
        "altCityName": "Phoenix",
        "fullName": "Phoenix Suns",
        "triCode": "PHX",
        "teamId": "1610612756",
        "nickname": "Suns",
        "urlName": "suns",
        "confName": "West",
        "divName": "Pacific"
    },
    {
        "isNBAFranchise": true,
        "city": "Portland",
        "altCityName": "Portland",
        "fullName": "Portland Trail Blazers",
        "triCode": "POR",
        "teamId": "1610612757",
        "nickname": "Trail Blazers",
        "urlName": "blazers",
        "confName": "West",
        "divName": "Northwest"
    },
    {
        "isNBAFranchise": false,
        "city": "Real Madrid",
        "altCityName": "Real Madrid",
        "fullName": "Real Madrid Real Madrid",
        "triCode": "RMD",
        "teamId": "12315",
        "nickname": "Real Madrid",
        "urlName": "real_madrid",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Sacramento",
        "altCityName": "Sacramento",
        "fullName": "Sacramento Kings",
        "triCode": "SAC",
        "teamId": "1610612758",
        "nickname": "Kings",
        "urlName": "kings",
        "confName": "West",
        "divName": "Pacific"
    },
    {
        "isNBAFranchise": true,
        "city": "San Antonio",
        "altCityName": "San Antonio",
        "fullName": "San Antonio Spurs",
        "triCode": "SAS",
        "teamId": "1610612759",
        "nickname": "Spurs",
        "urlName": "spurs",
        "confName": "West",
        "divName": "Southwest"
    },
    {
        "isNBAFranchise": false,
        "city": "Shanghai",
        "altCityName": "Shanghai",
        "fullName": "Shanghai Shanghai Sharks",
        "triCode": "SDS",
        "teamId": "12329",
        "nickname": "Shanghai Sharks",
        "urlName": "shanghai_sharks",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Toronto",
        "altCityName": "Toronto",
        "fullName": "Toronto Raptors",
        "triCode": "TOR",
        "teamId": "1610612761",
        "nickname": "Raptors",
        "urlName": "raptors",
        "confName": "East",
        "divName": "Atlantic"
    },
    {
        "isNBAFranchise": false,
        "city": "USA",
        "altCityName": "USA",
        "fullName": "USA USA",
        "triCode": "USA",
        "teamId": "1610616843",
        "nickname": "USA",
        "urlName": "usa",
        "confName": "East",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "city": "USA Celebrities",
        "altCityName": "USA Celebrities",
        "fullName": "USA Celebrities USA Celebrities",
        "triCode": "USA",
        "teamId": "1610616840",
        "nickname": "USA Celebrities",
        "urlName": "usa_celebrities",
        "confName": "West",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "city": "Utah",
        "altCityName": "Utah",
        "fullName": "Utah Jazz",
        "triCode": "UTA",
        "teamId": "1610612762",
        "nickname": "Jazz",
        "urlName": "jazz",
        "confName": "West",
        "divName": "Northwest"
    },
    {
        "isNBAFranchise": true,
        "city": "Washington",
        "altCityName": "Washington",
        "fullName": "Washington Wizards",
        "triCode": "WAS",
        "teamId": "1610612764",
        "nickname": "Wizards",
        "urlName": "wizards",
        "confName": "East",
        "divName": "Southeast"
    },
    {
        "isNBAFranchise": false,
        "city": "West",
        "altCityName": "West",
        "fullName": "West West",
        "triCode": "WST",
        "teamId": "1610616834",
        "nickname": "West",
        "urlName": "west",
        "confName": "West",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "city": "World",
        "altCityName": "World",
        "fullName": "World World",
        "triCode": "WLD",
        "teamId": "1610616844",
        "nickname": "World",
        "urlName": "world",
        "confName": "East",
        "divName": ""
    }
];

export default TEAMS;